### ISSUE TITLE
movieGenre Table script required

### ISSUE THREAD

**Issue by Taru-garg** [Taru-garg/theTVguide#10]
Movies must be mapped to the genres according to the gen_id in the genre table. This can be done through python or SQL.

**Comment by nitingrover425** [comment]
What exactly do you need me to do? 
Should I add another attribute in moviesTable corresponding to matching gen_id for each movie?

**Comment by Taru-garg** [comment]
Well, there is a table for that already so it can be added to that.
I guess that can be done in SQL much more easily than in python.
