### ISSUE TITLE
Fixes required in moviesTable.sql / insertQueryScript.py

### ISSUE THREAD

**Issue by Taru-garg** [Taru-garg/theTVguide#7]
Currently, there are a few fixes required in moviesTable.sql or insertQueryScript.py:-

1. mov_id must be treated as an integer (currently as string)
2. Null must be inserted for the columns where there is no data

**Comment by nitingrover425** [comment]
The first fix is done. 
But I am not sure there are any problems with the NULL value not being inserted where no data is present.

**Comment by Taru-garg** [comment]
So basically, the definition for that table (movies) isn't the same as what the insert statement says.

```CREATE TABLE MOVIES (
    mov_id INTEGER PRIMARY KEY,
    title VARCHAR(50) NOT NULL,
    overview VARCHAR(MAX),
    length INTEGER,             --in minutes
    language VARCHAR(50),
    initial_release_date DATE,
    release_country VARCHAR(20)
);
```
It expects length, language and release_country. It should be fine if it is defined what columns are exactly getting inserted but if that isn't done then the statement fails to execute.
Since in the script, it isn't explicitly defined as to what values we are inserting it should be fixed either by putting null for the column or specifying what we are inserting.

**Comment by nitingrover425** [comment]
Done.

**Comment by Taru-garg** [comment]
Great!
